AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create KMS in Audit Account for SNS topics. This Cloudforamation must need to execute in Audit account'      
Resources:
  myKMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: This will used by SNS to send notification with encryption
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: Key policy created by CloudTrail
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'            
          - Sid: Enable event service Permissions
            Effect: Allow
            Principal:
                Service: events.amazonaws.com
            Action: 
                - "kms:Decrypt"
                - "kms:GenerateDataKey"
            Resource: "*"
      Tags:
        - Key: Name
          Value: SNS-Encryption
  myKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
        AliasName: alias/SNS-Encryption
        TargetKeyId:
            Ref: myKMSKey   
Outputs:
  KMSKey: 
    Description: "KMS key for SNS topic encryption"
    Value: !Ref myKMSKey
    Export: 
      Name: !Sub "${AWS::StackName}-KMSKEY"
